Repository temporalio/sdk-php, pull requests merged in 2022-08, with the labels that each got.

#215 fix: don't fail on null workflow result history
  src/Internal/Client/WorkflowStub.php
  tests/Unit/Internal/Client/WorkflowStubTestCase.php
Labels: Bug, enhancement

#216 Enum as a input for workflow
  src/DataConverter/JsonConverter.php
  src/DataConverter/Type.php
  tests/Fixtures/src/Activity/SimpleActivity.php
  tests/Fixtures/src/Workflow/ScalarEnumWorkflow.php
  tests/Fixtures/src/Workflow/SimpleEnumWorkflow.php
  tests/Functional/Client/EnumTestCase.php
Labels: enhancement

#218 fix: don't wait implicitly for child scope
  src/Internal/Transport/Request/GetChildWorkflowExecution.php
  src/Internal/Workflow/Process/Process.php
  src/Internal/Workflow/Process/Scope.php
  src/Worker/Transport/Command/Request.php
  src/Worker/Transport/Command/RequestInterface.php
  tests/Fixtures/data/Test_CancelledWithCompensationWorkflow.log
  tests/Fixtures/src/Workflow/AsyncClosureWorkflow.php
  tests/Functional/Client/AsyncClosureTestCase.php
  tests/Functional/Client/AwaitTestCase.php
  tests/Functional/Client/ClientTestCase.php
Labels: Bug

#234 Ability to return associative array from an activity
  src/DataConverter/JsonConverter.php
  src/DataConverter/Type.php
  tests/Unit/DataConverter/DataConverterTestCase.php
Labels: enhancement

#232 Issue 211. Test for readonly properties
  .github/workflows/run-test-suite.yml
  composer.json
  tests/Unit/DTO/DTOMarshallingTestCase.php
  tests/Unit/DTO/Readonly/ReadonlyPropertiesDTO.php
  tests/Unit/DTO/Readonly/ReadonlyPropertiesTestCase.php
Labels: enhancement

#217 Possibility to configure temporal test server host
  phpunit.xml
  testing/Readme.md
  testing/src/Environment.php
  testing/src/WithoutTimeSkipping.php
  testing/src/WorkflowTestCase.php
Labels: enhancement

#235 Add error output for temporal test server
  testing/src/Environment.php
Labels: enhancement

#237 Update php to 8.0
  .github/workflows/code-style.yml
  .github/workflows/run-test-suite.yml
  .github/workflows/security-check.yml
  composer.json
Labels: enhancement

#238 Fix: abandoned child workflow start
  src/Internal/Workflow/ChildWorkflowStub.php
  src/Workflow.php
  src/Workflow/ChildWorkflowStubInterface.php
  tests/Fixtures/src/Workflow/AbandonedChildWithTimerWorkflow.php
  tests/Fixtures/src/Workflow/ParentWithAbandonedChildWorkflow.php
  tests/Functional/Client/AwaitTestCase.php
  tests/Functional/Client/ExternalWorkflowTestCase.php
Labels: Bug
