Repository temporalio/sdk-php, pull requests merged in 2023-07, with the labels that each got.

#263 Wrapper for multiple task queues
  testing/Readme.md
  testing/src/Environment.php
Labels: Question, enhancement, Tests

#299 [CI] Add Windows tests
  .github/workflows/run-test-suite.yml
Labels: enhancement, Tests

#259 feat: allow to return array of objects
  src/DataConverter/JsonConverter.php
  src/DataConverter/Type.php
  src/Workflow/WorkflowRunInterface.php
  tests/Fixtures/src/Activity/SimpleActivity.php
  tests/Fixtures/src/Workflow/ArrayOfObjectsWorkflow.php
  tests/Functional/Client/TypeArrayOfObjectsTestCase.php
Labels: enhancement

#334 Fix marshalling/unmarshalling of nullable object type
  src/Internal/Marshaller/Type/ObjectType.php
  tests/Unit/DTO/Type/ObjectType/ObjectTypeTestCase.php
  tests/Unit/DTO/Type/ObjectType/Stub/NullableProperty.php
Labels: Bug

#331 Fix exceptions propagation from Signal methods
  src/Activity/ActivityCancellationType.php
  src/Internal/Declaration/WorkflowInstance.php
  src/Internal/Declaration/WorkflowInstance/SignalQueue.php
  src/Internal/Declaration/WorkflowInstanceInterface.php
  src/Internal/Workflow/Process/Process.php
  src/Internal/Workflow/Process/Scope.php
  src/Internal/Workflow/WorkflowContext.php
  tests/Fixtures/src/Workflow/LoopWithSignalCoroutinesWorkflow.php
  tests/Fixtures/src/Workflow/SignalExceptionsWorkflow.php
  tests/Functional/Client/AwaitTestCase.php
  tests/Functional/Client/FailureTestCase.php
  tests/Functional/Client/UntypedWorkflowStubTestCase.php
  tests/docker-compose.yaml
Labels: Bug
