Repository temporalio/sdk-php, pull requests merged in 2023-01, with the labels that each got.

#267 Feature: pass error into activity finalizer
  src/Internal/Transport/Router/InvokeActivity.php
  tests/Unit/Router/InvokeActivityTestCase.php
Labels: Feature

#270 [Critical bug] fix: default `Activity`'s `taskQueue`
  src/Activity/ActivityOptions.php
  tests/Fixtures/data/Test_ActivityStubWorkflow.log
  tests/Fixtures/data/Test_BinaryPayload.log
  tests/Fixtures/data/Test_CancelledWithCompensationWorkflow.log
  tests/Fixtures/data/Test_ContinueAsNew.log
  tests/Fixtures/data/Test_ExecuteChildStubWorkflow.log
  tests/Fixtures/data/Test_ExecuteChildStubWorkflow_02.log
  tests/Fixtures/data/Test_ExecuteChildWorkflow.log
  tests/Fixtures/data/Test_ExecuteProtoWorkflow.log
  tests/Fixtures/data/Test_ExecuteSimpleDTOWorkflow.log
  tests/Fixtures/data/Test_ExecuteSimpleWorkflowWithSequenceInBatch.log
  tests/Fixtures/data/Test_ExecuteSimpleWorkflow_1.log
  tests/Fixtures/data/Test_ExecuteWorkflowWithParallelScopes.log
  tests/Fixtures/data/Test_MultipleWorkflowsInSingleWorker.log
  tests/Fixtures/data/Test_PromiseChaining.log
  tests/Fixtures/data/Test_SideEffect.log
  tests/Fixtures/data/Test_Timer.log
  tests/Unit/DTO/ActivityOptionsTestCase.php
Labels: enhancement

#278 Marshaller upgrade
  psalm.xml
  src/DataConverter/Type.php
  src/Internal/Marshaller/Mapper/AttributeMapper.php
  src/Internal/Marshaller/Marshaller.php
  src/Internal/Marshaller/MarshallingRule.php
  src/Internal/Marshaller/Meta/Marshal.php
  src/Internal/Marshaller/Meta/MarshalArray.php
  src/Internal/Marshaller/RuleFactoryInterface.php
  src/Internal/Marshaller/Type/ArrayType.php
  src/Internal/Marshaller/Type/DateIntervalType.php
  src/Internal/Marshaller/Type/DateTimeType.php
  src/Internal/Marshaller/Type/EnumType.php
  src/Internal/Marshaller/Type/NullableType.php
  src/Internal/Marshaller/Type/ObjectType.php
  src/Internal/Marshaller/Type/RuleFactoryInterface.php
  src/Internal/Marshaller/Type/Type.php
  src/Internal/Marshaller/TypeFactory.php
  src/Internal/Marshaller/TypeFactoryInterface.php
  src/Internal/Support/DateTime.php
  src/Internal/Support/Inheritance.php
  tests/Fixtures/src/Activity/SimpleActivity.php
  tests/Fixtures/src/Workflow/ScalarEnumWorkflow.php
  tests/Fixtures/src/Workflow/SimpleEnumWorkflow.php
  tests/Functional/Client/EnumTestCase.php
  tests/Unit/DTO/DTOMarshallingTestCase.php
  tests/Unit/DTO/Type/ArrayType/ArrayDto.php
  tests/Unit/DTO/Type/ArrayType/ArrayTestCase.php
  tests/Unit/DTO/Type/DateIntervalType/DateIntervalTestCase.php
  tests/Unit/DTO/Type/DateIntervalType/Stub/DateIntervalDto.php
  tests/Unit/DTO/Type/DateTimeType/DateTimeTestCase.php
  tests/Unit/DTO/Type/DateTimeType/Stub/DateTimeDto.php
  tests/Unit/DTO/Type/EnumType/EnumTestCase.php
  tests/Unit/DTO/Type/EnumType/Stub/EnumDto.php
  tests/Unit/DTO/Type/EnumType/Stub/ScalarEnum.php
  tests/Unit/DTO/Type/EnumType/Stub/SimpleEnum.php
  tests/Unit/DTO/Type/ObjectType/ObjectTypeTestCase.php
  tests/Unit/DTO/Type/ObjectType/Stub/ChildDto.php
  tests/Unit/DTO/Type/ObjectType/Stub/Nested1.php
  tests/Unit/DTO/Type/ObjectType/Stub/Nested2.php
  tests/Unit/DTO/Type/ObjectType/Stub/Nested3.php
  tests/Unit/DTO/Type/ObjectType/Stub/NestedParent.php
  tests/Unit/DTO/Type/ObjectType/Stub/ParentDto.php
  tests/Unit/DTO/Type/ObjectType/Stub/ReadonlyProperty.php
Labels: Feature, enhancement
