Repository temporalio/sdk-php, pull requests merged in 2024-03, with the labels that each got.

#403 Update protobuf messages
  composer.json
  testing/api/testservice/GPBMetadata/Dependencies/Gogoproto/Gogo.php
  testing/api/testservice/GPBMetadata/Temporal/Api/Testservice/V1/RequestResponse.php
  testing/api/testservice/GPBMetadata/Temporal/Api/Testservice/V1/Service.php
  testing/api/testservice/Temporal/Api/Testservice/V1/GetCurrentTimeResponse.php
  testing/api/testservice/Temporal/Api/Testservice/V1/SleepRequest.php
  testing/api/testservice/Temporal/Api/Testservice/V1/SleepUntilRequest.php
  testing/proto/dependencies/gogoproto/gogo.proto
  testing/proto/temporal/api/testservice/v1/request_response.proto
  testing/scripts/generate-proto.php
Labels: enhancement

#406 Fix FailureConverter when an exception CallStack contains an incomplete set of keys
  psalm-baseline.xml
  src/Exception/Failure/FailureConverter.php
  tests/Unit/Exception/FailureConverterTestCase.php
Labels: Bug

#408 Add generation of API documentation
  .github/workflows/docs.yml
  phpdoc.dist.xml
  src/Activity.php
  src/Activity/ActivityCancellationType.php
  src/Activity/ActivityContextInterface.php
  src/Activity/ActivityInfo.php
  src/Activity/ActivityInterface.php
  src/Activity/ActivityOptions.php
  src/Activity/LocalActivityInterface.php
  src/Activity/LocalActivityOptions.php
  src/Client/GRPC/ServiceClient.php
  src/Client/GRPC/ServiceClientInterface.php
  src/Client/Schedule/Info/ScheduleActionResult.php
  src/Client/Schedule/Info/ScheduleDescription.php
  src/Client/Schedule/Info/ScheduleListEntry.php
  src/Client/Schedule/Info/ScheduleListInfo.php
  src/Client/Schedule/Policy/SchedulePolicies.php
  src/Client/Schedule/Schedule.php
  src/Client/Schedule/Spec/CalendarSpec.php
  src/Client/Schedule/Spec/IntervalSpec.php
  src/Client/Schedule/Spec/Range.php
  src/Client/Schedule/Spec/ScheduleSpec.php
  src/Client/Schedule/Spec/ScheduleState.php
  src/Client/Update/LifecycleStage.php
  src/Client/WorkflowClientInterface.php
  src/Client/WorkflowExecutionHistory.php
  src/Client/WorkflowOptions.php
  src/Client/WorkflowStubInterface.php
  src/Common/CronSchedule.php
  src/Interceptor/ActivityInboundInterceptor.php
  src/Interceptor/Header.php
  src/Interceptor/PipelineProvider.php
  src/Interceptor/Trait/ActivityInboundInterceptorTrait.php
  src/Interceptor/Trait/WorkflowClientCallsInterceptorTrait.php
  src/Interceptor/Trait/WorkflowInboundCallsInterceptorTrait.php
  src/Interceptor/Trait/WorkflowOutboundCallsInterceptorTrait.php
  src/Interceptor/Trait/WorkflowOutboundRequestInterceptorTrait.php
  src/Interceptor/WorkflowClientCallsInterceptor.php
  src/Interceptor/WorkflowInboundCallsInterceptor.php
  src/Interceptor/WorkflowOutboundCallsInterceptor.php
  src/Interceptor/WorkflowOutboundRequestInterceptor.php
  src/Internal/Client/WorkflowStarter.php
  src/Internal/Declaration/Reader/WorkflowReader.php
  src/Promise.php
  src/Worker/ChildWorkflowCancellationType.php
  src/Worker/LoopInterface.php
  src/Worker/WorkerFactoryInterface.php
  src/Worker/WorkerInterface.php
  src/WorkerFactory.php
  src/Workflow.php
  src/Workflow/ChildWorkflowCancellationType.php
  src/Workflow/ChildWorkflowOptions.php
  src/Workflow/ContinueAsNewOptions.php
  src/Workflow/ScopedContextInterface.php
  src/Workflow/WorkflowContextInterface.php
  src/Workflow/WorkflowExecution.php
  src/Workflow/WorkflowExecutionInfo.php
  src/Workflow/WorkflowExecutionStatus.php
  src/Workflow/WorkflowRunInterface.php
Labels: Documentation
